### ISSUE TITLE
Can not read download of undefined

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/hashbase#34]
TypeError: Cannot read property 'download' of undefined
    at Protocol.add (/home/pfrazee/hashbase/lib/archiver.js:378:36)
    at emitOne (events.js:96:13)
    at Protocol.emit (events.js:189:7)
    at Protocol._onopen (/home/pfrazee/hashbase/node_modules/hypercore-protocol/index.js:290:8)
    at Protocol._onmessage (/home/pfrazee/hashbase/node_modules/hypercore-protocol/index.js:311:17)
    at Protocol._parseMessage (/home/pfrazee/hashbase/node_modules/hypercore-protocol/index.js:365:10)
    at Protocol._parse (/home/pfrazee/hashbase/node_modules/hypercore-protocol/index.js:330:37)
    at Protocol._write (/home/pfrazee/hashbase/node_modules/hypercore-protocol/index.js:238:8)
    at doWrite (/home/pfrazee/hashbase/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/pfrazee/hashbase/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Protocol.Writable.write (/home/pfrazee/hashbase/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

**Comment by pfrazee** [comment]
Still occurring. I patched with a temp solution and am logging.
